language: scala
script: sbt -Dsbt.log.noformat=true +publish
jdk:
- oraclejdk7
env:
  global:
  - secure: Psh7SokZcTVxctMI84JpG5xg4jYkV9Jw2egET9cv2oRujP0HTIh8BWkaxFHRIEoAXbxzPK3/SiPtVeQSYgGlCRBSCtSJ8pcgNYmOXMgsyRX87J8eBlbgGE/k38tU4Y77BW6zBOrFfXuOJl0YanFWmIFPuYb0Lb2u0OdTXd+X/wU=
  - secure: B/LRRQrzky0AxIfELxyAXfRvRXCmmHz6MBDux4Z4fOU6smH/IQWUoQFRYeiG9eotJi5xljSG7XI50M+7l9REtCFsjNA7CUQl2zm6vT1ClrFnhEWIgtOQQ/DwbL829MqkCxxokob703PKjyOrSu5wOq87VWhNa6UjnTZaI7wNl9U=
