branches:
  only:
    - master
language: scala
script: sbt -Dsbt.log.noformat=true +compile +make-site +publish
jdk:
  - oraclejdk7
env:
  global:
  - secure: LZqtbvSqVPpycaMLC9FnCaEs70WLt9tr+477t6jdCwyUgkaRfcBvLVeh/EsH4RJW+GtvNqmpZ43dpUGrnxZktFvZz+1LdPNtVggLza+ysMd/KlVlSXT1Re1NvArc4nE9Po+hQws26ehvlk2+BKh0e5SfXRU/3+NDs1H0bgtkQVU=
  - secure: aqp+oGdQuHoKktOM9r6AEvNqSWCXnmCF6hAZMgVY1A5PFM9sW+gKqe91WfjCOikv/RSv1Vq/rD4KXxGeW/+M4RntGjhBXKuyQ3nqBZQL5LcpPp9xY15JUW1FteBHam4DuAOxyuudJSONmbb8KdC33siBHHcJe5/diqAUazXFMg0=
